# Generated by Django 5.1 on 2024-11-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('cod_asig', models.UUIDField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueClase',
            fields=[
                ('cod_bloque_clase', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bloque_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('bloque', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'bloque_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('cod_clase', models.UUIDField(primary_key=True, serialize=False)),
                ('sala_real', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cod_docente', models.UUIDField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignaturaSeccion',
            fields=[
                ('cod_doc_asig_sec', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'docente_asignatura_seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('cod_mod', models.UUIDField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('cod_sec', models.UUIDField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('cod_sem', models.UUIDField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
    ]
