# Generated by Django 5.1.3 on 2024-12-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('cod_asig', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('bloque', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'bloque_horario',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cod_docente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('cod_mod', models.SmallAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'modalidad',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('cod_sec', models.BigAutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'seccion',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('cod_sem', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('cod_clase', models.BigAutoField(primary_key=True, serialize=False)),
                ('sala_real', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('cod_sala', models.ForeignKey(blank=True, db_column='cod_sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.sala')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='BloqueClase',
            fields=[
                ('cod_bloque_clase', models.BigAutoField(primary_key=True, serialize=False)),
                ('bloque', models.ForeignKey(db_column='bloque', on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.bloquehorario')),
                ('cod_clase', models.ForeignKey(db_column='cod_clase', on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.clase')),
            ],
            options={
                'db_table': 'bloque_clase',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignaturaSeccion',
            fields=[
                ('cod_doc_asig_sec', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_asig', models.ForeignKey(blank=True, db_column='cod_asig', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.asignatura')),
                ('cod_docente', models.ForeignKey(blank=True, db_column='cod_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.docente')),
                ('cod_sec', models.ForeignKey(blank=True, db_column='cod_sec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.seccion')),
            ],
            options={
                'db_table': 'docente_asignatura_seccion',
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='cod_doc_asig_sec',
            field=models.ForeignKey(blank=True, db_column='cod_doc_asig_sec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.docenteasignaturaseccion'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cod_mod',
            field=models.ForeignKey(blank=True, db_column='cod_mod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.modalidad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cod_sem',
            field=models.ForeignKey(blank=True, db_column='cod_sem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga_planificacion.semestre'),
        ),
    ]
