# Generated by Django 5.1.3 on 2024-12-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('cod_ac', models.BigAutoField(primary_key=True, serialize=False)),
                ('btu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ac',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_ciudad', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('cod_controlador', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'controlador',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('cod_edificio', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.SmallAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='MarcaAc',
            fields=[
                ('cod_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'marca_ac',
            },
        ),
        migrations.CreateModel(
            name='ModeloAc',
            fields=[
                ('cod_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'modelo_ac',
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('cod_ori', models.SmallAutoField(primary_key=True, serialize=False)),
                ('orientacion', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'orientacion',
            },
        ),
        migrations.CreateModel(
            name='TipoAc',
            fields=[
                ('cod_tipo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_ac',
            },
        ),
        migrations.CreateModel(
            name='TipoError',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_error',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('cod_tipo_sensor', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_sensor',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('cod_zona', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_comuna', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('cod_ciudad', models.ForeignKey(blank=True, db_column='cod_ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.ciudad')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('cod_clima', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cod_comuna', models.ForeignKey(blank=True, db_column='cod_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.comuna')),
            ],
            options={
                'db_table': 'clima',
            },
        ),
        migrations.CreateModel(
            name='EstadoAc',
            fields=[
                ('cod_estado_ac', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('cod_ac', models.ForeignKey(blank=True, db_column='cod_ac', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.ac')),
                ('cod_estado', models.ForeignKey(blank=True, db_column='cod_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.estado')),
            ],
            options={
                'db_table': 'estado_ac',
            },
        ),
        migrations.AddField(
            model_name='ac',
            name='cod_marca',
            field=models.ForeignKey(blank=True, db_column='cod_marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.marcaac'),
        ),
        migrations.AddField(
            model_name='ac',
            name='cod_modelo',
            field=models.ForeignKey(blank=True, db_column='cod_modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.modeloac'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('cod_sala', models.BigAutoField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=25, unique=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('cod_controlador', models.OneToOneField(blank=True, db_column='cod_controlador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.controlador')),
                ('cod_edificio', models.ForeignKey(blank=True, db_column='cod_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.edificio')),
                ('cod_ori', models.ForeignKey(blank=True, db_column='cod_ori', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.orientacion')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.AddField(
            model_name='ac',
            name='cod_sala',
            field=models.ForeignKey(blank=True, db_column='cod_sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.sala'),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('cod_sede', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('cod_comuna', models.ForeignKey(blank=True, db_column='cod_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.comuna')),
            ],
            options={
                'db_table': 'sede',
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='cod_sede',
            field=models.ForeignKey(blank=True, db_column='cod_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.sede'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('cod_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('cod_controlador', models.ForeignKey(blank=True, db_column='cod_controlador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.controlador')),
                ('cod_tipo_sensor', models.ForeignKey(blank=True, db_column='cod_tipo_sensor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tiposensor')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('cod_lectura', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=25)),
                ('fecha_hora', models.DateTimeField()),
                ('cod_sensor', models.ForeignKey(blank=True, db_column='cod_sensor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.sensor')),
            ],
            options={
                'db_table': 'lectura',
            },
        ),
        migrations.AddField(
            model_name='ac',
            name='cod_tipo',
            field=models.ForeignKey(blank=True, db_column='cod_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tipoac'),
        ),
        migrations.CreateModel(
            name='SalaTipoError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('sala', models.ForeignKey(blank=True, db_column='cod_sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.sala')),
                ('tipo_error', models.ForeignKey(blank=True, db_column='tipo_error', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tipoerror')),
            ],
            options={
                'db_table': 'sala_tipo_error',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='cod_zona',
            field=models.ForeignKey(blank=True, db_column='cod_zona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.zona'),
        ),
    ]
