# Generated by Django 5.1.3 on 2024-12-02 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, db_column='cod_sede', null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.sede'),
        ),
    ]
