# Generated by Django 5.1 on 2024-11-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre del cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cod_usuario', models.UUIDField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de usuario')),
                ('usuario', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('cod_cargo', models.ForeignKey(blank=True, db_column='cod_cargo', null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.cargo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
