# Generated by Django 5.1 on 2024-11-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('cod_ac', models.UUIDField(primary_key=True, serialize=False)),
                ('btu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('cod_clima', models.UUIDField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'clima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('cod_controlador', models.UUIDField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'controlador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('cod_edificio', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.UUIDField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoAc',
            fields=[
                ('cod_estado_ac', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estado_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('cod_lectura', models.UUIDField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'lectura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaAc',
            fields=[
                ('cod_marca', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'marca_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloAc',
            fields=[
                ('cod_modelo', models.UUIDField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'modelo_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('cod_ori', models.UUIDField(primary_key=True, serialize=False)),
                ('orientacion', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'orientacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('cod_sala', models.UUIDField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=25, unique=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('cod_sensor', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAc',
            fields=[
                ('cod_tipo', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('cod_tipo_sensor', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_ciudad', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('cod_zona', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_comuna', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('cod_ciudad', models.ForeignKey(blank=True, db_column='cod_ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.ciudad')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('cod_sede', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('cod_comuna', models.ForeignKey(blank=True, db_column='cod_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.comuna')),
            ],
            options={
                'db_table': 'sede',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='cod_zona',
            field=models.ForeignKey(blank=True, db_column='cod_zona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.zona'),
        ),
    ]
